from __future__ import annotations

from dataclasses import dataclass, asdict
import json
import re
from typing import Any

import requests

from app.config import settings
from app.pdf_tools import PdfPage, page_excerpt


@dataclass
class PageScript:
    page: int
    narration: str
    focus: str
    highlight_terms: list[str]


@dataclass
class WalkthroughScript:
    title: str
    full_script: str
    page_scripts: list[PageScript]
    source: str

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        return data


def write_walkthrough_script(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    language = "English"
    if settings.openai_api_key:
        try:
            return _write_with_openai(pages, prospect_name, target_company, language, max_minutes)
        except Exception as exc:
            print(f"OpenAI script generation failed, falling back locally: {exc}")

    return _write_locally(pages, prospect_name, target_company, language, max_minutes)


def _write_with_openai(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    target_words = _target_words(max_minutes)
    page_targets = _page_word_targets(pages, target_words)
    page_payload = [
        {
            "page": page.page_number,
            "heading": page.heading,
            "target_words": page_targets[index],
            "lines": page.lines[:140],
            "full_text_excerpt": page_excerpt(page.text, limit=5200),
        }
        for index, page in enumerate(pages)
    ]

    system_prompt = (
        "You are a senior growth consultant creating a direct PDF walkthrough voiceover "
        "for the company receiving this report. The narration must sound calm, emotionally natural, "
        "warm, clear, human, persuasive, and confident. Speak directly to the viewer using you, your team, "
        "and your business. Use only the PDF text supplied by the user. Do not invent metrics, problems, "
        "recommendations, or facts."
    )
    user_prompt = {
        "prospect_name": prospect_name or "the prospect",
        "target_company": target_company or "the target company",
        "language": language,
        "target_minutes": max_minutes,
        "target_total_words": target_words,
        "pages": page_payload,
        "writing_rules": [
            "Explain the page as numbered business pointers: Point 1, Point 2, and so on.",
            "When a page heading is supplied, use that PDF heading as the page focus and as the first pointer.",
            "For each pointer, say what it means, why it matters, and what can be improved, but only if that is supported by the PDF text.",
            "Address the viewer directly using 'you', 'your team', and 'your business'.",
            "Never use the word formed by c-l-i-e-n-t in narration, titles, focus labels, or on-screen text.",
            "Do not write speaker notes or internal instructions. The copy goes directly to the viewer.",
            "Do not mention outreach, pitching, prospecting, or sales conversation.",
            "Do not repeatedly say visual, visuals, or visual section.",
            "Use warm consultative phrasing, natural pauses, varied sentence length, and light emotional emphasis. Add occasional ellipses for thoughtful pauses, but do not overuse them.",
            "Never say this was generated by AI. Never sound like a script reader.",
            "Write only in clear, natural English.",
        ],
        "output_contract": {
            "title": "short video title",
            "page_scripts": [
                {
                    "page": "page number",
                    "narration": "spoken narration close to that page's target_words, structured around numbered pointers",
                    "focus": "short on-screen focus label; prefer the supplied PDF heading",
                    "highlight_terms": "3-8 exact short pointer phrases copied from this page's PDF text; include the PDF heading first when present",
                }
            ],
        },
    }

    response = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.openai_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(user_prompt, ensure_ascii=False)},
            ],
            "temperature": 0.45,
        },
        timeout=90,
    )
    response.raise_for_status()
    content = response.json()["choices"][0]["message"]["content"]
    payload = _parse_json_response(content)

    page_scripts = []
    for index, item in enumerate(payload.get("page_scripts", [])):
        page = pages[min(index, len(pages) - 1)]
        focus = str(item.get("focus") or page.heading or f"Page {index + 1}").strip()
        highlight_terms = [str(term).strip() for term in item.get("highlight_terms", []) if str(term).strip()]
        highlight_terms = _dedupe_terms(([page.heading] if page.heading else []) + highlight_terms)
        page_scripts.append(
            PageScript(
                page=int(item.get("page", index + 1)),
                narration=str(item.get("narration", "")).strip(),
                focus=focus,
                highlight_terms=highlight_terms,
            )
        )

    if not page_scripts:
        raise ValueError("OpenAI returned no page scripts.")

    page_scripts = _ensure_target_length(page_scripts, pages, prospect_name, target_company, language, target_words)
    full_script = "\n\n".join(item.narration for item in page_scripts)
    title = str(payload.get("title") or _default_title(target_company)).strip()
    return WalkthroughScript(title=title, full_script=full_script, page_scripts=page_scripts, source="openai")


def _parse_json_response(content: str) -> dict[str, Any]:
    content = content.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", content, flags=re.DOTALL | re.IGNORECASE)
    if fence:
        content = fence.group(1).strip()
    return json.loads(content)


def _write_locally(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    company = target_company.strip() or "your business"
    report_owner = target_company.strip() or "business"
    prospect = prospect_name.strip() or "there"
    is_hinglish = language.lower() in {"hinglish", "hindi", "hi"}
    target_words = _target_words(max_minutes)
    page_targets = _page_word_targets(pages, target_words)
    scripts: list[PageScript] = []

    for index, page in enumerate(pages):
        focus = page.heading or _focus_from_text(page.text, page.page_number)
        points = _extract_points(page)
        target_for_page = page_targets[index]

        if is_hinglish:
            opener = (
                f"Page {page.page_number} par aapke {report_owner} report ka ye section detail mein dekhte hain. "
                f"Is section ka main focus hai: {focus}. "
            )
            narration = _build_hinglish_detail(opener, points, target_for_page)
        else:
            opener = (
                f"On page {page.page_number}, let us look closely at this section of your {report_owner} report. "
                f"The main focus here is {focus}. "
            )
            narration = _build_english_detail(opener, points, target_for_page)

        scripts.append(
            PageScript(
                page=page.page_number,
                narration=narration,
                focus=focus,
                highlight_terms=_highlight_terms_for_page(page),
            )
        )

    intro = (
        f"Hi {prospect}, this walkthrough is prepared for {company}. I will take you through the key findings, what they mean, and where your team can improve next."
        if not is_hinglish
        else f"Hi {prospect}, ye walkthrough {company} ke liye prepared hai. Main aapko key findings, unka meaning, aur next improvements simple way mein explain karunga."
    )
    closing = (
        "From here, your next step is to turn these observations into a focused action plan, prioritize the quickest improvements, and measure progress week by week."
        if not is_hinglish
        else "Yahan se aapka next step hoga ki in observations ko focused action plan mein convert karein, quickest improvements prioritize karein, aur week by week progress measure karein."
    )

    if scripts:
        scripts[0].narration = f"{intro} {scripts[0].narration}"
        scripts[-1].narration = f"{scripts[-1].narration} {closing}"

    full_script = "\n\n".join(item.narration for item in scripts)
    scripts = _ensure_target_length(scripts, pages, prospect_name, target_company, language, target_words)
    full_script = "\n\n".join(item.narration for item in scripts)
    return WalkthroughScript(
        title=_default_title(company),
        full_script=full_script,
        page_scripts=scripts,
        source="local",
    )


def _default_title(company: str) -> str:
    company = company.strip() or "Prospect"
    return f"{company} report walkthrough"


def _focus_from_text(text: str, page_number: int) -> str:
    text = text.strip()
    if not text:
        return f"report section on page {page_number}"

    candidates = re.split(r"(?<=[.!?])\s+|\n+", text)
    candidates = [item.strip(" :-|") for item in candidates if len(item.strip()) >= 8]
    first = candidates[0] if candidates else text[:90]
    words = first.split()
    return " ".join(words[:10])


def _highlight_terms_for_page(page: PdfPage) -> list[str]:
    terms = ([page.heading] if page.heading else []) + [box.label for box in page.highlights[:8]]
    return _dedupe_terms(terms)[:8]


def _dedupe_terms(terms: list[str]) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for term in terms:
        cleaned = " ".join((term or "").split())
        if not cleaned:
            continue
        key = re.sub(r"[^a-z0-9]+", "", cleaned.lower())
        if key in seen:
            continue
        seen.add(key)
        deduped.append(cleaned)
    return deduped


def _summarize_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if not text:
        return "this report section helps your team understand what to prioritize next."

    sentences = re.split(r"(?<=[.!?])\s+", text)
    useful = [sentence.strip() for sentence in sentences if len(sentence.strip()) > 20]
    if not useful:
        useful = [text]

    summary = " ".join(useful[:2])
    words = summary.split()
    if len(words) > 55:
        summary = " ".join(words[:55]) + "..."
    return summary


def _target_words(max_minutes: int) -> int:
    minutes = max(1, min(int(max_minutes or 1), 6))
    return minutes * 140


def _page_word_targets(pages: list[PdfPage], total_words: int) -> list[int]:
    weights = [max(len(page.text.split()), 80) for page in pages]
    total_weight = sum(weights) or len(pages)
    targets = [max(90, round(total_words * weight / total_weight)) for weight in weights]
    difference = total_words - sum(targets)
    if targets:
        targets[-1] += difference
    return targets


def _extract_points(page: PdfPage) -> list[str]:
    candidates: list[str] = []

    for line in page.lines:
        cleaned = _clean_point(line)
        if cleaned:
            candidates.append(cleaned)

    if len(candidates) < 3:
        sentences = re.split(r"(?<=[.!?])\s+", page.text)
        for sentence in sentences:
            cleaned = _clean_point(sentence)
            if cleaned:
                candidates.append(cleaned)

    unique: list[str] = []
    seen: set[str] = set()
    for candidate in candidates:
        key = candidate.lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(candidate)

    return unique[:22] or [_summarize_text(page.text)]


def _clean_point(text: str) -> str:
    text = clean_script_text(text)
    text = re.sub(r"^[\-•*–—\d.)\s]+", "", text).strip()
    if len(text) < 12:
        return ""
    if len(text.split()) > 38:
        text = " ".join(text.split()[:38]) + "..."
    return text


def clean_script_text(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def _build_hinglish_detail(opener: str, points: list[str], target_words: int) -> str:
    narration_parts = [opener]
    if not points:
        points = ["Is page ka section aapki team ko next priority samajhne mein help karta hai."]

    index = 0
    while _word_count(" ".join(narration_parts)) < target_words:
        point = points[index % len(points)]
        if index < len(points):
            narration_parts.append(
                f"Point {index + 1}: report yahan ye mention karti hai: {point}. "
                "Aapko simple way mein iska business impact samajhna chahiye. "
                "Agar yahan gap ya opportunity hai, to pehle highest-impact fix choose karein, phir usko weekly measure karein. "
            )
        else:
            narration_parts.append(
                "Yahan message clear rehna chahiye: sirf observation nahi, next action bhi. "
                f"{point} ko priority, effort, aur expected impact ke basis par plan karein. "
            )
        index += 1
        if index > 80:
            break

    return " ".join(narration_parts).strip()


def _build_english_detail(opener: str, points: list[str], target_words: int) -> str:
    narration_parts = [opener]
    if not points:
        points = ["This report section helps your team understand what to prioritize next."]

    index = 0
    while _word_count(" ".join(narration_parts)) < target_words:
        point = points[index % len(points)]
        if index < len(points):
            narration_parts.append(
                f"Point {index + 1}: the report is calling out {point}. "
                "Now, here is the business meaning. "
                "This is not just an observation; it is a decision point for your team. "
                "If it is a gap, fix the highest-impact part first. If it is already working, use it as leverage for the next stage of growth. "
            )
        else:
            narration_parts.append(
                "So the recommendation is simple: turn this into an action item. "
                f"Use {point} to decide what should be improved first, what can wait, and what your team should measure every week. "
            )
        index += 1
        if index > 80:
            break

    return " ".join(narration_parts).strip()


def _ensure_target_length(
    page_scripts: list[PageScript],
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    target_words: int,
) -> list[PageScript]:
    current_words = _word_count("\n\n".join(script.narration for script in page_scripts))
    if current_words >= int(target_words * 0.88):
        return page_scripts

    words_needed = target_words - current_words
    per_page_extra = max(60, words_needed // max(len(page_scripts), 1))
    page_lookup = {page.page_number: page for page in pages}
    is_hinglish = language.lower() in {"hinglish", "hindi", "hi"}

    expanded: list[PageScript] = []
    for script in page_scripts:
        page = page_lookup.get(script.page)
        if not page:
            expanded.append(script)
            continue

        points = _extract_points(page)
        extra = (
            _build_hinglish_detail("", points, per_page_extra)
            if is_hinglish
            else _build_english_detail("", points, per_page_extra)
        )
        expanded.append(
            PageScript(
                page=script.page,
                narration=f"{script.narration} {extra}".strip(),
                focus=script.focus,
                highlight_terms=_dedupe_terms(script.highlight_terms or _highlight_terms_for_page(page))[:8],
            )
        )

    return expanded


def _word_count(text: str) -> int:
    return len(re.findall(r"\S+", text or ""))
