from __future__ import annotations

from dataclasses import dataclass, asdict
import json
import re
from typing import Any

import requests

from app.config import settings
from app.pdf_tools import PdfPage, page_excerpt


@dataclass
class PageScript:
    page: int
    narration: str
    focus: str
    highlight_terms: list[str]


@dataclass
class WalkthroughScript:
    title: str
    full_script: str
    page_scripts: list[PageScript]
    source: str

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        return data


def write_walkthrough_script(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    language = "English"
    if settings.openai_api_key:
        try:
            return _write_with_openai(pages, prospect_name, target_company, language, max_minutes)
        except Exception as exc:
            print(f"OpenAI script generation failed, falling back locally: {exc}")

    return _write_locally(pages, prospect_name, target_company, language, max_minutes)


def _write_with_openai(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    target_words = _target_words(max_minutes)
    page_targets = _page_word_targets(pages, target_words)
    page_payload = [
        {
            "page": page.page_number,
            "heading": page.heading,
            "target_words": page_targets[index],
            "lines": page.lines[:140],
            "full_text_excerpt": page_excerpt(page.text, limit=5200),
        }
        for index, page in enumerate(pages)
    ]

    system_prompt = (
        "You are a senior growth consultant creating a direct PDF walkthrough voiceover "
        "for the company receiving this report. The narration must sound calm, emotionally natural, "
        "warm, clear, human, persuasive, and confident. Speak directly to the viewer using you, your team, "
        "and your business. Use only the PDF text supplied by the user. Do not invent metrics, problems, "
        "recommendations, or facts."
    )
    user_prompt = {
        "prospect_name": prospect_name or "the prospect",
        "target_company": target_company or "the target company",
        "language": language,
        "target_minutes": max_minutes,
        "target_total_words": target_words,
        "pages": page_payload,
        "writing_rules": [
            "Explain the page as numbered business pointers: Point 1, Point 2, and so on.",
            "When a page heading is supplied, use that PDF heading as the page focus and as the first pointer.",
            "Each pointer must come from a distinct line, metric, finding, recommendation, or heading in that page's PDF text.",
            "For each pointer, say what the PDF says, what it means, why it matters, and what can be improved, but only if that is supported by the PDF text.",
            "Address the viewer directly using 'you', 'your team', and 'your business'.",
            "Never use the word formed by c-l-i-e-n-t in narration, titles, focus labels, or on-screen text.",
            "Do not write speaker notes or internal instructions. The copy goes directly to the viewer.",
            "Do not mention outreach, pitching, prospecting, or sales conversation.",
            "Do not repeatedly say visual, visuals, or visual section.",
            "Do not pad the narration. If a page has limited text, keep that page concise instead of repeating the same idea.",
            "Avoid generic filler phrases like 'this is not just an observation' or 'the recommendation is simple'.",
            "Use warm consultative phrasing, natural pauses, varied sentence length, and light emotional emphasis. Add occasional ellipses for thoughtful pauses, but do not overuse them.",
            "Never say this was generated by AI. Never sound like a script reader.",
            "Write only in clear, natural English.",
        ],
        "output_contract": {
            "title": "short video title",
            "page_scripts": [
                {
                    "page": "page number",
                    "narration": "spoken narration close to that page's target_words, structured around numbered pointers",
                    "focus": "short on-screen focus label; prefer the supplied PDF heading",
                    "highlight_terms": "3-5 concise pointer labels copied from this page's PDF text; these are used for camera movement labels only, not visible highlight boxes",
                }
            ],
        },
    }

    response = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.openai_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(user_prompt, ensure_ascii=False)},
            ],
            "temperature": 0.45,
        },
        timeout=90,
    )
    response.raise_for_status()
    content = response.json()["choices"][0]["message"]["content"]
    payload = _parse_json_response(content)

    page_scripts = []
    for index, item in enumerate(payload.get("page_scripts", [])):
        page = pages[min(index, len(pages) - 1)]
        focus = str(item.get("focus") or page.heading or f"Page {index + 1}").strip()
        highlight_terms = [str(term).strip() for term in item.get("highlight_terms", []) if str(term).strip()]
        highlight_terms = _dedupe_terms(([page.heading] if page.heading else []) + highlight_terms)
        page_scripts.append(
            PageScript(
                page=int(item.get("page", index + 1)),
                narration=str(item.get("narration", "")).strip(),
                focus=focus,
                highlight_terms=highlight_terms[:6],
            )
        )

    if not page_scripts:
        raise ValueError("OpenAI returned no page scripts.")

    page_scripts = _ensure_target_length(page_scripts, pages, prospect_name, target_company, language, target_words)
    full_script = "\n\n".join(item.narration for item in page_scripts)
    title = str(payload.get("title") or _default_title(target_company)).strip()
    return WalkthroughScript(title=title, full_script=full_script, page_scripts=page_scripts, source="openai")


def _parse_json_response(content: str) -> dict[str, Any]:
    content = content.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", content, flags=re.DOTALL | re.IGNORECASE)
    if fence:
        content = fence.group(1).strip()
    return json.loads(content)


def _write_locally(
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    max_minutes: int,
) -> WalkthroughScript:
    company = target_company.strip() or "your business"
    company_for_sentence = company.rstrip(".")
    prospect = prospect_name.strip() or "there"
    is_hinglish = language.lower() in {"hinglish", "hindi", "hi"}
    target_words = _target_words(max_minutes)
    page_targets = _page_word_targets(pages, target_words)
    scripts: list[PageScript] = []
    point_counter = 1

    for index, page in enumerate(pages):
        focus = clean_script_text(page.heading or _focus_from_text(page.text, page.page_number))
        points = _extract_points(page)
        target_for_page = page_targets[index]
        selected_points = _points_for_target(_dedupe_focus_points(points, focus), target_for_page)

        if is_hinglish:
            narration = _build_hinglish_detail(selected_points, target_for_page, focus, point_counter)
        else:
            narration = _build_english_detail(selected_points, target_for_page, focus, point_counter)
        point_counter += max(1, len(selected_points))

        scripts.append(
            PageScript(
                page=page.page_number,
                narration=narration,
                focus=focus,
                highlight_terms=selected_points,
            )
        )

    intro = (
        f"Hi {prospect}, this walkthrough covers the key findings for {company_for_sentence} and the improvements to prioritize next."
        if not is_hinglish
        else f"Hi {prospect}, ye walkthrough {company_for_sentence} ke key findings aur next improvements simple way mein explain karta hai."
    )
    closing = (
        "Next, turn these observations into a focused action plan and measure progress week by week."
        if not is_hinglish
        else "Ab in observations ko focused action plan mein convert karein aur week by week progress measure karein."
    )

    if scripts:
        scripts[0].narration = f"{intro} {scripts[0].narration}"
        scripts[-1].narration = f"{scripts[-1].narration} {closing}"

    full_script = "\n\n".join(item.narration for item in scripts)
    scripts = _ensure_target_length(scripts, pages, prospect_name, target_company, language, target_words)
    full_script = "\n\n".join(item.narration for item in scripts)
    return WalkthroughScript(
        title=_default_title(company),
        full_script=full_script,
        page_scripts=scripts,
        source="local",
    )


def _default_title(company: str) -> str:
    company = company.strip() or "Prospect"
    return f"{company} report walkthrough"


def _focus_from_text(text: str, page_number: int) -> str:
    text = text.strip()
    if not text:
        return f"report section on page {page_number}"

    candidates = re.split(r"(?<=[.!?])\s+|\n+", text)
    candidates = [item.strip(" :-|") for item in candidates if len(item.strip()) >= 8]
    first = candidates[0] if candidates else text[:90]
    words = first.split()
    return " ".join(words[:10])


def _highlight_terms_for_page(page: PdfPage) -> list[str]:
    return []


def _dedupe_terms(terms: list[str]) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for term in terms:
        cleaned = " ".join((term or "").split())
        if not cleaned:
            continue
        key = re.sub(r"[^a-z0-9]+", "", cleaned.lower())
        if key in seen:
            continue
        seen.add(key)
        deduped.append(cleaned)
    return deduped


def _dedupe_focus_points(points: list[str], focus: str) -> list[str]:
    cleaned_focus = _point_key(focus)
    result: list[str] = []
    seen: set[str] = set()
    for point in points:
        key = _point_key(point)
        if not key or key in seen:
            continue
        seen.add(key)
        if cleaned_focus and key == cleaned_focus:
            if not result:
                result.append(point)
            continue
        result.append(point)
    return result or points


def _summarize_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    if not text:
        return "the report gives a short finding that should be reviewed before choosing the next improvement."

    sentences = re.split(r"(?<=[.!?])\s+", text)
    useful = [sentence.strip() for sentence in sentences if len(sentence.strip()) > 20]
    if not useful:
        useful = [text]

    summary = " ".join(useful[:2])
    words = summary.split()
    if len(words) > 55:
        summary = " ".join(words[:55]) + "..."
    return summary


def _target_words(max_minutes: int) -> int:
    minutes = max(1, min(int(max_minutes or 1), 6))
    return minutes * 95


def _page_word_targets(pages: list[PdfPage], total_words: int) -> list[int]:
    weights = [max(len(page.text.split()), 80) for page in pages]
    total_weight = sum(weights) or len(pages)
    targets = [max(45, round(total_words * weight / total_weight)) for weight in weights]
    difference = total_words - sum(targets)
    if targets:
        targets[-1] += difference
    return targets


IMPORTANT_POINT_TERMS = {
    "analysis",
    "aeo",
    "answer",
    "audit",
    "benchmark",
    "campaign",
    "conversion",
    "customer",
    "entity",
    "engine",
    "favicon",
    "geo",
    "generative",
    "growth",
    "improve",
    "issue",
    "keyword",
    "knowledge",
    "lead",
    "lighthouse",
    "metric",
    "open",
    "opportunity",
    "organic",
    "overview",
    "page",
    "performance",
    "priority",
    "recommendation",
    "revenue",
    "risk",
    "schema",
    "score",
    "search",
    "seo",
    "serp",
    "social",
    "structured",
    "traffic",
    "vitals",
}


LOW_VALUE_POINT_PATTERNS = (
    r"^page\s*\d+(\s*/\s*\d+)?$",
    r"^saffron\s*ai$",
    r"^saffronedge$",
    r"^all rights reserved$",
    r"^confidential$",
    r"^table of contents$",
    r"^thank you\.?$",
)


def _extract_points(page: PdfPage) -> list[str]:
    scored: list[tuple[float, int, str]] = []

    if page.heading:
        heading = _clean_point(page.heading)
        if heading:
            scored.append((90.0, -1, heading))

    for position, line in enumerate(page.lines):
        cleaned = _clean_point(line)
        if cleaned:
            score = _point_score(cleaned, position, page.heading)
            if score > 0:
                scored.append((score, position, cleaned))

    if len(scored) < 4:
        sentences = re.split(r"(?<=[.!?])\s+", page.text)
        for position, sentence in enumerate(sentences, start=200):
            cleaned = _clean_point(sentence)
            if cleaned:
                score = _point_score(cleaned, position, page.heading)
                if score > 0:
                    scored.append((score, position, cleaned))

    selected: list[tuple[float, int, str]] = []
    seen: set[str] = set()
    for score, position, candidate in sorted(scored, key=lambda item: (-item[0], item[1])):
        key = _point_key(candidate)
        if key in seen:
            continue
        seen.add(key)
        selected.append((score, position, candidate))
        if len(selected) >= 8:
            break

    selected.sort(key=lambda item: item[1])
    return [candidate for _, _, candidate in selected] or [_summarize_text(page.text)]


def _clean_point(text: str) -> str:
    text = clean_script_text(text)
    text = re.sub(r"^[\-•*–—\d.)\s]+", "", text).strip()
    text = text.strip("\"'` ")
    if not text or _is_low_value_point(text):
        return ""
    if len(text.split()) > 38:
        text = " ".join(text.split()[:38]) + "..."
    return text


def _is_low_value_point(text: str) -> bool:
    cleaned = clean_script_text(text).strip(" :-|")
    if len(cleaned) < 8:
        return True

    lower = cleaned.lower()
    if re.search(r"https?://|www\.|@", lower):
        return True
    if re.fullmatch(r"[\W\d_]+", cleaned):
        return True
    if len(re.findall(r"[A-Za-z]", cleaned)) < 5:
        return True
    if sum(1 for char in cleaned if char.isdigit()) > max(4, len(cleaned) * 0.45):
        return True

    return any(re.fullmatch(pattern, lower) for pattern in LOW_VALUE_POINT_PATTERNS)


def _point_key(text: str) -> str:
    words = re.findall(r"[a-z0-9]+", text.lower())
    return " ".join(words[:18])


def _point_score(text: str, position: int, heading: str) -> float:
    if _is_low_value_point(text):
        return 0.0

    words = text.split()
    lower = text.lower()
    score = 18.0

    if 4 <= len(words) <= 18:
        score += 16.0
    elif len(words) <= 3:
        score -= 8.0
    elif len(words) > 30:
        score -= 5.0

    if re.search(r"\d|%|\$|rs\.?|inr|usd|x\b|:", lower):
        score += 12.0

    normalized_terms = set(re.findall(r"[a-z0-9]+", lower))
    score += sum(5.0 for term in IMPORTANT_POINT_TERMS if term in normalized_terms)

    if heading and _point_key(text) == _point_key(heading):
        score += 22.0

    if position < 12:
        score += max(0.0, 10.0 - position * 0.7)

    if lower.endswith("?"):
        score -= 6.0

    return score


def clean_script_text(text: str) -> str:
    replacements = {
        "â€”": "-",
        "â€“": "-",
        "â†’": " to ",
        "—": "-",
        "–": "-",
        "→": " to ",
        "←": " from ",
        "“": '"',
        "”": '"',
        "’": "'",
        "‘": "'",
        "â€œ": '"',
        "â€": '"',
        "â€™": "'",
        "â€˜": "'",
        "â€¢": "",
        "â€¦": "...",
        "Â": "",
    }
    cleaned = text or ""
    for bad, good in replacements.items():
        cleaned = cleaned.replace(bad, good)
    cleaned = _normalize_report_terms(cleaned)
    phrase_replacements = {
        "Applied Al": "Applied AI",
        "eitherkeepasavisualherosub-headline": "either keep it as a visual hero sub-headline",
        "andaddavisuallysmaller": "and add a visually smaller",
        "butcrawlable": "but crawlable",
        "orrestructuresothe": "or restructure so the",
        "includesthe": "includes the",
        "consultingkeyword": "consulting keyword",
    }
    for bad, good in phrase_replacements.items():
        cleaned = cleaned.replace(bad, good)
    cleaned = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", cleaned)
    cleaned = re.sub(r"(?<=[A-Za-z])(?=\d)", " ", cleaned)
    cleaned = re.sub(r"(?<=\d)(?=[A-Za-z])", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip()


def _normalize_report_terms(text: str) -> str:
    normalized = text or ""
    normalized = re.sub(r"\bOn\s*[-–—]?\s*[1lI]\s+Page\s+SEO\b", "On-Page SEO", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bOn\s+Page\s+SEO\b", "On-Page SEO", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bOn\s*[-–—]\s*Page\s+SEO\b", "On-Page SEO", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bOff\s*[-–—]?\s*Page\s+SEO\b", "Off-Page SEO", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bog\s*image\s*alt\s*attribute\b", "OG image alt attribute", normalized, flags=re.IGNORECASE)
    normalized = re.sub(r"\bog\s*description\b", "OG description", normalized, flags=re.IGNORECASE)
    return normalized


def _spoken_text(text: str) -> str:
    spoken = clean_script_text(text)
    spoken = re.sub(r"^\s*\d+\s*[.)]\s*", "", spoken)
    spoken = re.sub(r"\b(\d{1,3})\s*/\s*100\b", r"\1 out of 100", spoken)
    spoken = re.sub(r"\$\s*([0-9]+(?:\.[0-9]+)?)\s*B\b", r"\1 billion dollars", spoken, flags=re.IGNORECASE)
    spoken = re.sub(r"\bJSON\s*[- ]\s*LD\b", "JSON linked data", spoken, flags=re.IGNORECASE)
    spoken = re.sub(r"\bH\s*1\b", "H one heading", spoken, flags=re.IGNORECASE)
    spoken = re.sub(r"\bSEO\b", "Search Engine Optimization", spoken)
    spoken = re.sub(r"\bAEO\b", "Answer Engine Optimization", spoken)
    spoken = re.sub(r"\bGEO\b", "Generative Engine Optimization", spoken)
    spoken = re.sub(r"\bSERP\b", "Search Engine Results Page", spoken)
    spoken = re.sub(r"\bCTR\b", "click-through rate", spoken)
    spoken = re.sub(r"\bCPC\b", "cost per click", spoken)
    spoken = re.sub(r"\bOG\b", "Open Graph", spoken)
    spoken = re.sub(r"\bHQ\b", "headquarters", spoken)
    spoken = re.sub(r"\bCEO\b", "chief executive officer", spoken)
    spoken = re.sub(r"\bAI\b", "artificial intelligence", spoken)
    spoken = re.sub(r"\s+", " ", spoken)
    return spoken.strip()


def _same_point(point: str, focus: str) -> bool:
    point_key = _point_key(point)
    focus_key = _point_key(focus)
    if not point_key or not focus_key:
        return False
    return point_key == focus_key or point_key in focus_key or focus_key in point_key


def _build_hinglish_detail(points: list[str], target_words: int, focus: str = "", start_index: int = 1) -> str:
    narration_parts: list[str] = []
    if not points:
        points = ["Is page mein ek short finding hai jise next improvement decide karne se pehle review karna chahiye."]

    selected = _points_for_target(points, target_words)
    for index, point in enumerate(selected, start=1):
        spoken_point = _spoken_text(point)
        ordinal = start_index + index - 1
        transition = _hinglish_point_transition(ordinal)
        if index == 1 and _same_point(point, focus):
            if len(selected) > 1:
                narration_parts.append(f"{transition}: {_spoken_text(focus)}. Isko anchor samjhein; agla signal priority clear karega.")
                continue
            narration_parts.append(
                f"{transition}: {_spoken_text(focus)}. {_hinglish_focus_bridge(point)} {_hinglish_meaning(point)} {_hinglish_action(point)}"
            )
            continue
        narration_parts.append(
            f"{transition}: {spoken_point}. "
            f"{_hinglish_meaning(point)} "
            f"{_hinglish_action(point)}"
        )

    return clean_script_text(" ".join(narration_parts))


def _build_english_detail(points: list[str], target_words: int, focus: str = "", start_index: int = 1) -> str:
    narration_parts: list[str] = []
    if not points:
        points = ["The report gives a short finding that should be reviewed before choosing the next improvement."]

    selected = _points_for_target(points, target_words)
    for index, point in enumerate(selected, start=1):
        ordinal = start_index + index - 1
        transition = _english_point_transition(ordinal)
        if index == 1 and _same_point(point, focus):
            if len(selected) > 1:
                narration_parts.append(f"{transition}: {_spoken_text(focus)}. Use this as the anchor, then use the next signal to decide the priority.")
                continue
            narration_parts.append(
                f"{transition}: {_spoken_text(focus)}. {_english_focus_bridge(point)} {_business_meaning(point)} {_practical_action(point)}"
            )
            continue
        narration_parts.append(
            f"{_point_opener(ordinal, point)} {_business_meaning(point)} {_practical_action(point)}"
        )

    return clean_script_text(" ".join(narration_parts))


def _points_for_target(points: list[str], target_words: int) -> list[str]:
    if target_words <= 72:
        limit = 1
    elif target_words <= 130:
        limit = 2
    elif target_words <= 190:
        limit = 3
    elif target_words <= 270:
        limit = 4
    else:
        limit = 5
    return points[:limit]


def _point_opener(index: int, point: str) -> str:
    spoken_point = _spoken_text(point)
    return f"{_english_point_transition(index)}: {spoken_point}."


def _english_point_transition(index: int) -> str:
    return "First point" if index <= 1 else "Next point"


def _hinglish_point_transition(index: int) -> str:
    return "First point" if index <= 1 else "Next point"


def _english_focus_bridge(point: str) -> str:
    if _has_metric(point):
        return "That metric is the key signal here."
    return "This is the key item in this report."


def _hinglish_focus_bridge(point: str) -> str:
    if _has_metric(point):
        return "Ye metric yahan ka key signal hai."
    return "Ye report ka key item hai."


def _has_metric(text: str) -> bool:
    return bool(re.search(r"\d|%|\$|/100", text or ""))


def _business_meaning(point: str) -> str:
    lower = point.lower()
    if any(term in lower for term in ("knowledge graph", "entity card", "geo", "ai overview", "serp", "sitelink")):
        return "This matters because branded search and AI answers depend on clean entity signals, not just good-looking pages."
    if any(term in lower for term in ("schema", "structured data", "json-ld", "microdata")):
        return "This is a structure gap; without it, search engines and AI systems have less confidence in what the page represents."
    if any(term in lower for term in ("favicon", "open graph", "og:", "og title", "og description")):
        return "It looks small, but it shapes first impressions in browser tabs, previews, and shared links."
    if any(term in lower for term in ("internal link", "pagerank", "navigation")):
        return "This is about site architecture: when links are noisy, priority pages become harder for both users and search engines to read."
    if any(term in lower for term in ("seo", "search", "organic", "ranking", "keyword", "traffic")):
        return "This is a visibility signal. If this improves, the right people have a better chance of finding you before they shortlist someone else."
    if any(term in lower for term in ("conversion", "lead", "form", "enquiry", "demo", "contact")):
        return "This connects directly to lead flow, because even a small hesitation can reduce the number of qualified enquiries."
    if any(term in lower for term in ("speed", "technical", "error", "crawl", "index", "mobile", "loading")):
        return "This is friction. When technical friction stays unresolved, it quietly affects confidence, discovery, and momentum."
    if any(term in lower for term in ("content", "blog", "copy", "page", "landing")):
        return "This is a clarity signal. The page has to answer the important question fast, before attention moves elsewhere."
    if any(term in lower for term in ("campaign", "cpc", "ctr", "budget", "paid media", "paid search")):
        return "This is a performance signal; it tells you where spend, message, and audience quality are either aligned or drifting."
    if any(term in lower for term in ("review", "rating", "social", "brand", "trust")):
        return "This is a trust signal, and trust is what helps a visitor move from casual interest to real action."
    if any(term in lower for term in ("score", "audit", "benchmark", "analysis", "report")):
        return "Treat this like a priority marker. It turns a broad issue into something your team can actually rank and improve."
    return "The practical meaning is simple: this is a decision point, not just a note to leave inside the report."


def _practical_action(point: str) -> str:
    lower = point.lower()
    if any(term in lower for term in ("knowledge graph", "entity card", "geo", "ai overview", "serp", "sitelink")):
        return "The next move is to make entity signals consistent, strengthen the branded result, and check that the right pages appear in search."
    if any(term in lower for term in ("schema", "structured data", "json-ld", "microdata")):
        return "Add the relevant schema, validate it, and then watch whether search results understand the page more clearly."
    if any(term in lower for term in ("favicon", "open graph", "og:", "og title", "og description")):
        return "Fix the metadata and preview assets, then re-check browser tabs, social previews, and branded snippets."
    if any(term in lower for term in ("internal link", "pagerank", "navigation")):
        return "Reduce low-value links where needed, point authority toward priority pages, and make the path easier to scan."
    if any(term in lower for term in ("seo", "search", "organic", "ranking", "keyword", "traffic")):
        return "Start with the pages or keywords that have the clearest upside, then track movement every week."
    if any(term in lower for term in ("conversion", "lead", "form", "enquiry", "demo", "contact")):
        return "Tighten the call to action, reduce friction, and measure whether more qualified enquiries come through."
    if any(term in lower for term in ("speed", "technical", "error", "crawl", "index", "mobile", "loading")):
        return "Fix the highest-impact technical item first, then re-check the same metric so progress is visible."
    if any(term in lower for term in ("content", "blog", "copy", "page", "landing")):
        return "Sharpen the message, make the next step obvious, and connect the page to one measurable business outcome."
    if any(term in lower for term in ("campaign", "cpc", "ctr", "budget", "paid media", "paid search")):
        return "Compare spend against response quality, then shift budget toward the strongest combinations."
    return "Assign one owner, choose the first fix, and define the metric that will prove the change worked."


def _hinglish_meaning(point: str) -> str:
    lower = point.lower()
    if any(term in lower for term in ("seo", "search", "organic", "ranking", "keyword", "traffic")):
        return "Iska meaning visibility se hai: log aapko easily find kar paayen, tabhi comparison aur enquiry aage badhegi."
    if any(term in lower for term in ("conversion", "lead", "form", "enquiry", "demo", "contact")):
        return "Ye direct lead flow se connected hai, kyunki unclear message ya extra friction intent ko kam kar sakta hai."
    if any(term in lower for term in ("speed", "technical", "error", "crawl", "index", "mobile", "loading")):
        return "Ye technical friction ka signal hai, jo user confidence aur discoverability dono ko affect kar sakta hai."
    return "Simple meaning ye hai ki next decision lene se pehle is point ko priority ke saath review karna chahiye."


def _hinglish_action(point: str) -> str:
    lower = point.lower()
    if any(term in lower for term in ("seo", "search", "organic", "ranking", "keyword", "traffic")):
        return "Sabse clear opportunity wale pages ya keywords pick karke weekly movement track karein."
    if any(term in lower for term in ("conversion", "lead", "form", "enquiry", "demo", "contact")):
        return "Call to action clear karein, friction kam karein, aur qualified enquiries ka change measure karein."
    if any(term in lower for term in ("speed", "technical", "error", "crawl", "index", "mobile", "loading")):
        return "Highest-impact technical fix pehle karein, phir same metric ko re-check karein."
    return "Isse decide karein ki pehle kya improve karna hai, kya wait kar sakta hai, aur kaunsa metric progress prove karega."


def _ensure_target_length(
    page_scripts: list[PageScript],
    pages: list[PdfPage],
    prospect_name: str,
    target_company: str,
    language: str,
    target_words: int,
) -> list[PageScript]:
    return [
        PageScript(
            page=script.page,
            narration=clean_script_text(script.narration),
            focus=script.focus,
            highlight_terms=script.highlight_terms,
        )
        for script in page_scripts
    ]


def _word_count(text: str) -> int:
    return len(re.findall(r"\S+", text or ""))
